### ISSUE TITLE
Create a better solution to store and call the API key

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#11]
Right now it is stored in a variable in src/services/weatherservice.js and gets added to public.js upon doing npm start. Mission: make a better solution 🏆

**Comment by johemst** [comment]
Hey!
i can probably make it read the api key from a config json file or from a env variable or both 😀
What do you think @Bobeta ?

**Comment by Bobeta** [comment]
@johemst Sounds great! I usually prefer env variable but feel free to look around and make the decision based on what you think would be best for this case. Looking forward to see your work! 👍
