### ISSUE TITLE
Switch colors for widget background

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#16]
Add functionality so that the main background color can easily be changed and perhaps a demo switcher in the html example.

**Comment by shivasheeshyadav** [comment]
@Bobeta I would like to work on this issue. Assign it to me.

**Comment by Bobeta** [comment]
@shivasheeshyadav Sure, give it a shot! Thanks for showing interest mate! ❤️ Since you're not a collaborator yet, I can't assign it to you but feel free to make a Pull Request with your solution 👍

**Comment by shivasheeshyadav** [comment]
@Bobeta So you want the background color of index.html to be changed, and a color picker kind of thing to be included ?

**Comment by Bobeta** [comment]
@shivasheeshyadav That's correct 👍 are you up for it?

**Comment by shivasheeshyadav** [comment]
@Bobeta Yea, sure. Just one more doubt, I have to change the background color of row class which has an Aqua color by default, right ?
Also, as I'll be working for the first time with React, can you guide me as to which file in particular I have to make the changes.

**Comment by Benjadahl** [comment]
I have created a simple mockup in my fork, via the colourDemo.js file. 
![sample](http://i.imgur.com/c2evVgk.gif)
Sorry for the bad quality gif. You can check it out on commit 00b92.
I do not know if this is what you wanted, or a deeper react and sass intergration? However I am not experienced with those technologies, so I might have a hard time assisiting if that is what you wish. :)
