### ISSUE TITLE
Add a dist folder with JS files from only Reactive Weather without dependencies

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#17]
Create a dist folder and add the JS file of the generated script (without dependencies like React), both development and minified version.

**Comment by xRahul** [comment]
I don't get the "without dependencies like React" part. 
We can use webpack here to optimize the JS. But that'd include all the required libraries too.
Your code is already using ES5, so no need to transpile.
What are you using currently to build your code?

**Comment by Bobeta** [comment]
@xRahul Hi and thanks for showing interest! Sorry if I wasn't clear enough. I meant that we should only putt the reactive weather scripts in a dist folder without the required libraries for users that don't use JSX and bundling tools. So let's they have a app thats built using React, then they can easily add the script to their app without adding React all over again etc. 

Right now, it's using babelify/watchify and outputs everything bundled in public/js/main.js.

**Comment by Bobeta** [comment]
Created a new issue with a better explanation, closing this one for now.
