### ISSUE TITLE
Improving the structure and codebase

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#21]
Would be great with some refactoring & overall suggestions for improvements 👍

**Comment by tylerreckart** [comment]
@Bobeta I'd love to work on this one. Assign it over to me and I'll take it away

**Comment by Bobeta** [comment]
Awesome @tylerreckart, thanks for showing interest! Give it a shot! 👍

**Comment by luongthomas** [comment]
Is only one person allowed to work on this at a time?

**Comment by Bobeta** [comment]
@luongthomas you're welcome to work on it as well and I'll try to solve potential merge conflicts 👍
