### ISSUE TITLE
ESLint error

### ISSUE THREAD

**Issue by vkraucunas** [Bobeta/reactive-weather#22]
"reactive-weather/.eslintrc.json: Environment key "parser" is unknown" comes up in my Atom.

**Comment by johemst** [comment]
@vkraucunas i have the same problem. Is it related to a missing dependency or something?

**Comment by vkraucunas** [comment]
@Bobeta would you mind adding the Hacktober label to this issue?

**Comment by Bobeta** [comment]
Hacktoberfest added 👍 Thanks for helping with this issue @vkraucunas. Do you have the same problem as @johemst, not being able to load the apikey env?

**Comment by vkraucunas** [comment]
@Bobeta I had not gotten to that point because the eslint was erroring out. After I fixed and submitted that PR, I put the key where you instructed to on the Readme and had no issues.

**Comment by Bobeta** [comment]
@vkraucunas Alright, thanks for this & helping to solve the issue! ❤️
