### ISSUE TITLE
Add the Reactive Weather script in a separate folder

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#25]
- Generate the Reactive Weather script (without React) to a separate ES5 file in /dist folder. 
- Both unminified and minified version. 
- Test so that it works in a separate project where React is already imported.

**Comment by chrisgalvan** [comment]
Do we want to transpile to ES5 ? or do we want to keep ES6?

I have sent https://github.com/Bobeta/reactive-weather/pull/26 that keeps ES6 but I can change that if needed.
