### ISSUE TITLE
Make the default theme in SASS

### ISSUE THREAD

**Issue by Bobeta** [Bobeta/reactive-weather#9]
Make the default theme in SASS Instead of CSS as it is today. Create the .scss file in /src/sass and the generated css in public/css.

**Comment by dgrcode** [comment]
I'm looking for the src/sass folder and it seems to be gone. I'll have a look if a find the file

**Comment by Bobeta** [comment]
@dgrcode Hi mate, thanks for showing interest! I meant that the sass file should be created in that folder, sorry if I wasn't clear enough. There is a pull request with a suggestion for it right now, I'll take a look at it soon 👍

**Comment by Bobeta** [comment]
Thanks @nayangupta824 ❤️
